version: '3.7'

services:
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db_buyify'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    ports:
      - 3306:3306
    volumes:
      - /home/jpc/Desktop/mysql:/var/lib/mysql
    restart: 'no'