version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db_buyify'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'mascachapas'
    ports:
      - 3306:3306
    volumes:
      - /home/jpc/Desktop/mysql:/var/lib/mysql
    restart: 'no'

  redis:
    container_name: redis
    image: 'redis:latest'
    command: redis-server --requirepass mascachapas
    ports:
      - '6379:6379'

  buyify:
    container_name: buyify
    image: 'buyify/buyify-web:3'
    depends_on:
      - mysql
      - redis